[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[build]
  command = ""        # nu avem build
  publish = "public"  # doar ca să avem un folder de public (gol sau simplu)

[[redirects]]
  from = "/api/contact"
  to = "/.netlify/functions/contact"
  status = 200

[build.environment]
  NODE_VERSION = "18"
